apiVersion: apps/v1
kind: Deployment
metadata:
  name: splunk-defaults
  labels:
    app: splunk
    role: splunk-defaults
    tier: management
spec:
  selector:
    matchLabels:
      name: splunk-defaults
  replicas: 1
  template:
    metadata:
      labels:
        app: splunk
        role: splunk-defaults
        tier: management
        name: splunk-defaults
    spec:
      containers:
      - name: splunk-defaults
        image: httpd
        ports:
        - containerPort: 80
        volumeMounts:
        - name: httpd-data-www
          mountPath: /usr/local/apache2/htdocs/
      volumes:
      - name: httpd-data-www
        configMap: 
          name: /usr/local/apache2/htdocs/
