---
- name: Set mgmt port
  ini_file:
    dest: "{{ splunk.home }}/etc/system/local/web.conf"
    section: settings
    option: "mgmtHostPort"
    value: "0.0.0.0:{{ splunk.svc_port }}"
    owner: "{{ splunk.user }}"
    group: "{{ splunk.group }}"
